# This is a basic workflow to help you get started with Actions

name: Scheduled Auto-merge Workflow

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  pull_request:
    branches: ['main']

  schedule:
    # 4AM PT / 7AM PT, https://crontab.guru/every-hour
    - cron: 0 4 * * *

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "sceheduled-auto-merge"
  scheduled-auto-merge:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Set Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            mdx:
              - '**/*.mdx'
            allChanges:
              - added|deleted|modified: '**'
            addedContent:
              - added: '_content/**'
          list-files: 'csv'

      - name: Verify added mdx content
        uses: pvul/check-files-action@main
        if: |
          (
            steps.filter.outputs.allChanges_count == '1'
            steps.filter.outputs.addedContent == 'true' &&
            steps.filter.outputs.mdx == 'true'
          )
        env:
          filePath: ${{ steps.filter.outputs.addedContent_files }}

      - name: Install Yarn dependencies (for gray-matter)
        uses: borales/actions-yarn@v4
        if: |
          (
            steps.filter.outputs.allChanges_count == '1'
            steps.filter.outputs.addedContent == 'true' &&
            steps.filter.outputs.mdx == 'true'
          )
        with:
          cmd: add gray-matter

      - name: Yarn run scheduled-post
        uses: borales/actions-yarn@v4
        with:
          cmd: run scheduled-post ${{ steps.filter.outputs.addedContent_files }} # runs `yarn run scheduled-post`

      - name: Auto-commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: '📅 Automated changes to scheduled post'
          file_pattern: '_content/*.mdx'

      - name: Auto-approve PR
        uses: juliangruber/approve-pull-request-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          number: ${{ github.event.pull_request.number }}

      - name: Auto-merge PR
        uses: peter-evans/enable-pull-request-automerge@v2
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          pull-request-number: ${{ github.event.pull_request.number }}
          merge-method: squash
